environment:
  nodejs_version: 12

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm run winbuild
  - 7z a -tzip -mx9 BloodHound-win32-ia32.zip BloodHound-win32-ia32
  - 7z a -tzip -mx9 BloodHound-win32-x64.zip BloodHound-win32-x64

artifacts:
  - path: BloodHound-win32-ia32.zip
    name: BloodHound-win32-ia32
  - path: BloodHound-win32-x64.zip
    name: BloodHound-win32-x64

deploy:
  - provider: GitHub
    release: BloodHound Rolling
    description: 'Rolling release of BloodHound compiled from source ($(APPVEYOR_REPO_COMMIT)). Not necessarily stable. Automatically kept up to date with master, so ignore the commits since tag'
    artifact: BloodHound-win32-ia32,BloodHound-win32-x64
    force_update: true
    auth_token:
      secure: 9E4/AX+ecgXB482XLGCgpdLL5hlWJOUywGKREcRL0iD+YBU/ABXJOGXYHLeKQIgv


# Don't actually build.
build: off

branches:
  only:
    - master