import React from 'react';

const Opsec = () => {
    return (
        <>
            <p>
                There are several forensic artifacts generated by the techniques
                described above. For instance, lateral movement via PsExec will
                generate 4697 events on the target system. If the target
                organization is collecting and analyzing those events, they may
                very easily detect lateral movement via PsExec.
            </p>

            <p>
                Additionally, an EDR product may detect your attempt to inject
                into lsass and alert a SOC analyst. There are many more opsec
                considerations to keep in mind when abusing administrator
                privileges. For more information, see the References tab.
            </p>
        </>
    );
};

export default Opsec;
